### ISSUE TITLE
2024/12/26 - New error

### ISSUE THREAD

**Issue by hollak71** [anpigon/obsidian-book-search-plugin#128]
This plugin hs been working fine for me for a couple of week now, and I'm loving it.

Today I started getting errors, so I grabbed the text from the Obsidian Console:

Error: Request failed, status 429
    at new t (app.js:1:1925609)
    at PU (app.js:1:1925801)
    at app.js:1:1926480
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
getByQuery @ plugin:obsidian-book-search-plugin:6
await in getByQuery (async)
searchBook @ plugin:obsidian-book-search-plugin:9
eval @ plugin:obsidian-book-search-plugin:9
plugin:obsidian-book-search-plugin:12 Error: Request failed, status 429
    at new t (app.js:1:1925609)
    at PU (app.js:1:1925801)
    at app.js:1:1926480
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
createNewBookNote @ plugin:obsidian-book-search-plugin:12
await in createNewBookNote (async)
eval @ plugin:obsidian-book-search-plugin:9

**Comment by MattMaginniss** [comment]
+1 Have been using this plugin for a teal a year and running into this as well. Fully updated to 0.7.5 as well

**Comment by Xeelix** [comment]
+, same problem.

I fixed this by specifying API key in the extension settings: Google API Settings -> Set API Key

how to get API key: https://developers.google.com/books/docs/v1/using

**Comment by luckylat** [comment]
Thanks, the response may be 429 because the default API may have a rate limit on the number of searches by all users using default search. Please use generated individual API to avoid the error.

Ref: #47

**Comment by cquenelle** [comment]
same problem here. solution was to follow googles instructions:
make new project
make new api key (unrestricted)
enable books api on the project

**Comment by cquenelle** [comment]
whoops, its already in the readme:

Here's how to create and use one:

Create a project on [Google Cloud](https://console.cloud.google.com/projectcreate)
Enable the Books API for your project using the [Books API page](https://console.cloud.google.com/apis/library/books.googleapis.com)
Create an API key for your Google Cloud project using the [Google Cloud Credentials](https://console.cloud.google.com/apis/credentials) page
To limit the security risks of losing that key, you can edit it, and click on "Restrict key" under "API restrictions", then select only the "Books API" API
Add the API key to the settings of the Book Search plugin, under "Set API Key"
Once added, click on "Save", then "API Check"
